In [81]:
import pandas as pd

df = pd.read_csv("Crop_recommendation.csv")
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [82]:
x = df.drop(['label'], axis=1)

In [83]:
from sklearn import preprocessing

Y = df['label']
encode = preprocessing.LabelEncoder()
y = encode.fit_transform(Y)
print("Label length: ",len(y))


label_encoder_mapping = dict(zip(encode.classes_, encode.transform(encode.classes_)))
print("Label and Encoded Value:")
for label, encoded_value in label_encoder_mapping.items():
    print(f"{label}: {encoded_value}")

Label length:  2200
Label and Encoded Value:
apple: 0
banana: 1
blackgram: 2
chickpea: 3
coconut: 4
coffee: 5
cotton: 6
grapes: 7
jute: 8
kidneybeans: 9
lentil: 10
maize: 11
mango: 12
mothbeans: 13
mungbean: 14
muskmelon: 15
orange: 16
papaya: 17
pigeonpeas: 18
pomegranate: 19
rice: 20
watermelon: 21

In [84]:
# from sklearn import model_selection

# x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.2, random_state=42)
# print(len(x_train),len(y_train),len(x_test),len(y_test))




# stratified_split = model_selection.StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

# for train_index, test_index in stratified_split.split(x, y):
#     x_train, x_test = x.iloc[train_index], x.iloc[test_index]
#     y_train, y_test = y[train_index], y[test_index]

# print(len(x_train), len(y_train), len(x_test), len(y_test))







import pandas as pd
from sklearn import preprocessing
from sklearn.utils import shuffle
# Create a new DataFrame for convenience
df_encoded = x.copy()
df_encoded['label'] = y

# Determine the number of unique labels
unique_labels = df_encoded['label'].nunique()

# Initialize lists to store training and testing indices
train_indices = []
test_indices = []

# Split indices manually while ensuring balanced distribution
for i in range(unique_labels):
    label_indices = df_encoded[df_encoded['label'] == i].index
    split_point = int(0.8 * len(label_indices))
    print(split_point)
    train_indices.extend(label_indices[:split_point])
    test_indices.extend(label_indices[split_point:])

# Create training and testing sets using the indices
x_train = x.loc[train_indices].reset_index(drop=True)
x_test = x.loc[test_indices].reset_index(drop=True)
y_train = y[train_indices]
y_test = y[test_indices]

# Print the sizes of training and testing sets
print(len(x_train), len(y_train), len(x_test), len(y_test))

# Print the number of occurrences of each class in the training and test sets
from collections import Counter

train_counter = Counter(y_train)
test_counter = Counter(y_test)

print("Training set class distribution:")
for k, v in train_counter.items():
    print(f"Class {k}: {v} instances")

print("\nTest set class distribution:")
for k, v in test_counter.items():
    print(f"Class {k}: {v} instances")

80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
80
1760 1760 440 440
Training set class distribution:
Class 0: 80 instances
Class 1: 80 instances
Class 2: 80 instances
Class 3: 80 instances
Class 4: 80 instances
Class 5: 80 instances
Class 6: 80 instances
Class 7: 80 instances
Class 8: 80 instances
Class 9: 80 instances
Class 10: 80 instances
Class 11: 80 instances
Class 12: 80 instances
Class 13: 80 instances
Class 14: 80 instances
Class 15: 80 instances
Class 16: 80 instances
Class 17: 80 instances
Class 18: 80 instances
Class 19: 80 instances
Class 20: 80 instances
Class 21: 80 instances

Test set class distribution:
Class 0: 20 instances
Class 1: 20 instances
Class 2: 20 instances
Class 3: 20 instances
Class 4: 20 instances
Class 5: 20 instances
Class 6: 20 instances
Class 7: 20 instances
Class 8: 20 instances
Class 9: 20 instances
Class 10: 20 instances
Class 11: 20 instances
Class 12: 20 instances
Class 13: 20 instances
Class 14: 20 instances
Class 15: 20 instances
Class 16: 20 instances
Class 17: 20 instances
Class 18: 20 instances
Class 19: 20 instances
Class 20: 20 instances
Class 21: 20 instances

In [85]:
# from collections import Counter
# counter = Counter(y_test)

# # Print each unique number and its count
# for k, v in counter.items():
#     print(f"Number {k} is repeated {v} times")

In [90]:
x_test

       N    P    K  temperature   humidity        ph    rainfall
0     33  143  204    21.131608  91.957699  5.814435  122.539195
1     40  144  196    22.717507  92.254799  5.987263  107.028987
2      9  143  197    23.750331  92.881605  5.570021  117.660283
3     38  135  203    23.761218  93.661643  5.965551  100.825956
4     28  130  196    22.134506  94.676957  6.062356  112.920322
..   ...  ...  ...          ...        ...       ...         ...
435   97   12   47    25.287846  89.636679  6.765095   58.286977
436  110    7   45    26.638386  84.695469  6.189214   48.324286
437   96   18   50    25.331045  84.305338  6.904242   41.532187
438   83   23   55    26.897502  83.892415  6.463271   43.971937
439  120   24   47    26.986037  89.413849  6.260839   58.548767

[440 rows x 7 columns]

In [91]:
y_test

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21])

In [79]:
import numpy as np
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB(var_smoothing= 3.511191734215127e-05)
gnb.fit(x_train, y_train)

y_pred = gnb.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy: ", accuracy)
print("Classification Report: \n", classification_rep)

Accuracy:  0.990909090909091
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        20
           3       1.00      1.00      1.00        20
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20
           6       1.00      1.00      1.00        20
           7       1.00      1.00      1.00        20
           8       0.83      1.00      0.91        20
           9       1.00      1.00      1.00        20
          10       1.00      1.00      1.00        20
          11       1.00      1.00      1.00        20
          12       1.00      1.00      1.00        20
          13       1.00      1.00      1.00        20
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        20
          16       1.00      1.00      1.00        20
          17       1.00      1.00      1.00        20
          18       1.00      1.00      1.00        20
          19       1.00      1.00      1.00        20
          20       1.00      0.80      0.89        20
          21       1.00      1.00      1.00        20

    accuracy                           0.99       440
   macro avg       0.99      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440

In [80]:
import joblib

joblib.dump(gnb, 'gaussian_nb_model.joblib')
loaded_gnb = joblib.load('gaussian_nb_model.joblib')
y_pred = loaded_gnb.predict(x_test)
y_pred

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19,  8, 20, 20,  8, 20, 20, 20,  8,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20,  8, 20, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21])